(deftheme arcokai
  "A dark emacs theme. Created 2017-01-12.")

(custom-theme-set-faces
 'arcokai
 '(default ((t (:family "Cousine" :foundry "unknown" :width normal :height 113 :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "#cfdae3" :background "#383c4a" :stipple nil :inherit nil))))
 '(cursor ((t (:background "#545864"))))
 '(fixed-pitch ((t (:family "Monospace"))))
 '(variable-pitch ((((type w32)) (:font "-outline-Arial-normal-normal-normal-sans-*-*-*-*-p-*-iso8859-1")) (t (:family "Sans Serif"))))
 '(escape-glyph ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
 '(minibuffer-prompt ((t (:weight bold :foreground "#5294e2"))))
 '(highlight ((t (:foreground "#abb3bb" :background "#545864"))))
 '(region ((t (:foreground "#383c4a" :background "#cfdae3"))))
 '(shadow ((((class color grayscale) (min-colors 88) (background light)) (:foreground "grey50")) (((class color grayscale) (min-colors 88) (background dark)) (:foreground "grey70")) (((class color) (min-colors 8) (background light)) (:foreground "green")) (((class color) (min-colors 8) (background dark)) (:foreground "yellow"))))
 '(secondary-selection ((((class color) (min-colors 88) (background light)) (:background "yellow1")) (((class color) (min-colors 88) (background dark)) (:background "SkyBlue4")) (((class color) (min-colors 16) (background light)) (:background "yellow")) (((class color) (min-colors 16) (background dark)) (:background "SkyBlue4")) (((class color) (min-colors 8)) (:foreground "black" :background "cyan")) (t (:inverse-video t))))
 '(trailing-whitespace ((t (:background "#FF8C00"))))
 '(font-lock-builtin-face ((t (:foreground "#5294e2"))))
 '(font-lock-comment-delimiter-face ((default (:inherit (font-lock-comment-face)))))
 '(font-lock-comment-face ((t (:foreground "#79939f"))))
 '(font-lock-constant-face ((t (:foreground "#ab7eff"))))
 '(font-lock-doc-face ((t (:foreground "#79939f"))))
 '(font-lock-function-name-face ((t (:weight bold :foreground "#87D700"))))
 '(font-lock-keyword-face ((t (:weight bold :foreground "#5294e2"))))
 '(font-lock-negation-char-face ((t (:foreground "#ab7eff"))))
 '(font-lock-preprocessor-face ((t (:inherit (font-lock-builtin-face)))))
 '(font-lock-regexp-grouping-backslash ((t (:inherit (bold)))))
 '(font-lock-regexp-grouping-construct ((t (:inherit (bold)))))
 '(font-lock-string-face ((t (:foreground "#CDC673"))))
 '(font-lock-type-face ((t (:foreground "#FF1493"))))
 '(font-lock-variable-name-face ((t (:foreground "#FF8C00"))))
 '(font-lock-warning-face ((t (:foreground "#FF8C00" :background "#464a57"))))
 '(button ((t (:inherit (link)))))
 '(link ((t (:underline (:color foreground-color :style line) :foreground "#ab7eff"))))
 '(link-visited ((default (:inherit (link))) (((class color) (background light)) (:foreground "magenta4")) (((class color) (background dark)) (:foreground "violet"))))
 '(fringe ((t (:foreground "#99a1a7" :background "#464a57"))))
 '(header-line ((default (:inherit (mode-line))) (((type tty)) (:underline (:color foreground-color :style line) :inverse-video nil)) (((class color grayscale) (background light)) (:box nil :foreground "grey20" :background "grey90")) (((class color grayscale) (background dark)) (:box nil :foreground "grey90" :background "grey20")) (((class mono) (background light)) (:underline (:color foreground-color :style line) :box nil :inverse-video nil :foreground "black" :background "white")) (((class mono) (background dark)) (:underline (:color foreground-color :style line) :box nil :inverse-video nil :foreground "white" :background "black"))))
 '(tooltip ((((class color)) (:inherit (variable-pitch) :foreground "black" :background "lightyellow")) (t (:inherit (variable-pitch)))))
 '(mode-line ((t (:background "#464a57" :foreground "#99a1a7" :weight bold))))
 '(mode-line-buffer-id ((t (:weight bold :foreground "#87D700"))))
 '(mode-line-emphasis ((t (:foreground "#cfdae3"))))
 '(mode-line-highlight ((t (:weight bold :box nil :foreground "#5294e2"))))
 '(mode-line-inactive ((t (:weight normal :box (:line-width 1 :color nil :style pressed-button) :foreground "#4a83c6" :background "#383c4a"))))
 '(isearch ((t (:weight bold :foreground "#FF8C00" :background "#545864"))))
 '(isearch-fail ((((class color) (min-colors 88) (background light)) (:background "RosyBrown1")) (((class color) (min-colors 88) (background dark)) (:background "red4")) (((class color) (min-colors 16)) (:background "red")) (((class color) (min-colors 8)) (:background "red")) (((class color grayscale)) (:foreground "grey")) (t (:inverse-video t))))
 '(lazy-highlight ((t (:foreground "#bdc7cf" :background "#545864"))))
 '(match ((((class color) (min-colors 88) (background light)) (:background "yellow1")) (((class color) (min-colors 88) (background dark)) (:background "RoyalBlue3")) (((class color) (min-colors 8) (background light)) (:foreground "black" :background "yellow")) (((class color) (min-colors 8) (background dark)) (:foreground "white" :background "blue")) (((type tty) (class mono)) (:inverse-video t)) (t (:background "gray"))))
 '(next-error ((t (:inherit (region)))))
 '(query-replace ((t (:inherit (isearch))))))

(provide-theme 'arcokai)
